site_name: MkDocs Demo
site_url: http://athenian-programming.github.io/mkdocs-demo/
site_description: MkDocs Demo Documentation
site_author: Demo Team

repo_url: https://github.com/athenian-programming/mkdocs-demo
repo_name: 'GitHub Home'

# Uncomment this and insert you google ID
#google_analytics: ['UA-XXXXX7852-1', 'auto']

nav:
  - Home: index.md
  - Setup: setup.md
  - Repo Types:
    - Project: github-project.md
    - Organization: github-organization.md

theme:
  name: 'material'
  include_search_page: false   # Don't include MkDocs' JavaScript
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'images/owls.jpg'
  favicon: 'assets/images/favicon.ico'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: false   # true if website has code
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde